builds:
  - binary: s3
    main: ./cmd/s3
    ldflags: -s -w -X=github.com/barnybug/s3.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    hooks:
      post:
      - cmd: upx "{{ .Path }}"
        ignore: # upx fails on win arm64
        - goos: windows
          goarch: amd64

archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: binary
  replacements:
    darwin: mac
