language: go
go:
- 1.5
sudo: false
before_script:
- 'mkdir -p $GOPATH/bin && wget -q https://github.com/barnybug/cli53/releases/download/0.6.0/upx -O $GOPATH/bin/upx && chmod +x $GOPATH/bin/upx'
script:
- make test
before_deploy:
- make release
# workaround: https://github.com/travis-ci/travis-ci/issues/5145
- gem install mime-types -v 2.6.2
deploy:
  provider: releases
  api_key:
    secure: ogxurLU+Ak33qEYRZItJRBHj8TP7VTXjEiAmCBkVvatkFH6nnewfcLy3UliAnuu+8wp0YycYLyBmO+Zu+ZFLY3a9SN34yov/J6MvaSokoHgZZNzTvZsHf36+WYFI8mqBdeIXBuEj4qbdeOlP21LZjJA6SiIJjEyaXhGWn1zpN1k=
  file:
  - release/s3-linux-386
  - release/s3-linux-amd64
  - release/s3-linux-arm
  - release/s3-darwin-amd64
  - release/s3-windows-386.exe
  - release/s3-windows-amd64.exe
  on:
    repo: barnybug/s3
    tags: true
