name: CI
on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run BDD tests
      run: |
        go get github.com/gucumber/gucumber/cmd/gucumber
        # gucumber only works from under GOPATH...
        export GOPATH=$(go env GOPATH)
        export PATH=$PATH:$GOPATH/bin
        export GOSRC=$GOPATH/src/github.com/$GITHUB_REPOSITORY
        mkdir -p $GOPATH/src/github.com/barnybug
        ln -s $(pwd) $GOSRC
        cd $GOSRC
        gucumber

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
